### ISSUE TITLE
JsonSerializerSettings used by CompositionEndpointBuilder not surfaced via options

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#240]
I have a handler that directly queries a database for its response data to be added to the viewmodel.  The queries surface EFCore NetTopologySuite data types direct from the DB, such as Point, Coordinate, etc.  In order to serialize these types (for the wire) the serializer settings (whether NewtonSoft or System.Text.Json) require a NetTopologySuite custom converter to be registered with the serializer.  However, in this package's case we can't access the JsonSerializerSettings that's used when serializing the response.

I understand the current use case is to encapsulate the handling of "accept-casing" but is there possibly a way it can be modified to surface the settings so other configuration can be applied?  I can imagine other serialization use cases where this might be important too, such as NullValueHandling or reference loop handling.

**Comment by mauroservienti** [comment]
Hey @markphillips100 thanks for raising this. I see no problems in exposing those settings, or to be more precise in allowing settings to be set via configuration options.

I'll raise a PR to get this going.

**Comment by markphillips100** [comment]
That's great.  Thanks @mauroservienti

**Comment by mauroservienti** [comment]
@markphillips100 I raised #241, please take a look. Specifically to the configuration option (the code is from one of the tests): https://github.com/ServiceComposer/ServiceComposer.AspNetCore/blob/1be3831f42be447fc7e974d0a067ca7da6d43db1/src/ServiceComposer.AspNetCore.Endpoints.Tests/When_using_custom_serialization_settings.cs#L46-L50

Would the above work in your scenario?

**Comment by markphillips100** [comment]
I think it would @mauroservienti .  In my head I was initially thinking something like MVCs `AddJsonOptions` extension that applies the setting to controllers globally.  I think I prefer your approach better as it includes the request thereby allowing different settings per request should it be necessary.

**Comment by mauroservienti** [comment]
The feature is done and 1.8.0 will be available on NuGet shortly.

**Comment by markphillips100** [comment]
My turn to say wow @mauroservienti !  I much appreciate the speed you resolved this for me.
