### ISSUE TITLE
Support ICompositionRequestsHandler<TRequest>?

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#242]
Hi @mauroservienti .  This is more a question or topic for discussion than an issue.

I've been experimenting with MVC's model binding and if I could make use of it to avoid custom code for extracting route parameters, query string values, body or form content, etc.  The AspNetCore `ControllerBase` has a `TryUpdateModel` that looked promising so I've written a ModelBinder implementation that replicates most of that method's core function.

This allows me to write the following:

```
[HttpGet("path/{id:guid}")]
public async Task Handle(HttpRequest request)
{
    var requestModel = await _modelBinder.BindAsync<RequestModel>(request.HttpContext);
    ...
}
```
where `RequestModel` is a simple DTO that uses `[FromRoute]`, `[FromQuery]`, etc, to drive the model binding.  Same as controller actions basically.

What I really want to do though is just implement something like `ICompositionRequestsHandler<MyRequestModel>` and have the `Handle` method include a MyRequestModel parameter, already pre-bound. :-)

Any thoughts on how we might provide some extensibility to support automatic binding step?

**Comment by mauroservienti** [comment]
That looks interesting @markphillips100 and something I've always wanted to provide. There are two separate "features" to implement here:

- model binding support and the infrastructure to register binders and provide them to handlers
- generic/typed composition handlers

The first one is sort of simpler than the latter. My first idea about model binders was via an extension method to HttpRequest or similar: `request.GetIncomingModel<TModel>()`. (A better name maybe). And then add options to register binders or maybe reuse binders registered in ASP.Net if available (need to dive into how they register stuff).

The second one is more complex because it requires dynamic dispatch of method invocations. The thing is that now there is only one interface with a clear Handle method signature. If we introduce a generic one from the toolkit perspective the Handle method signature will be sort of unknown. Either it starts using the DLR (I dislike this option) or there is the need to introduce more complex structures to dynamically invoke the Handle method. In any case it's something I'd like to have. To disclose all my ideas I'd really love to have conventions based composition handlers: just define a class in CompositionHandlers namespace and the toolkit will discover methods to invoke based on attributes; similarly to what ASP.Net Core does with controllers.

One step at a time. I'll have a look at model binding first.

**Comment by markphillips100** [comment]
Here's the code I took from MVC's ControllerBase with a little tweak to use a CompositeValueProvider so I can supply mutliple value providers in one go for the model binding of an object (we aren't binding to an action's parameters here).

```
public class DefaultModelBinder : IModelBinder
{
    private readonly IOptions<JsonOptions> _jsonOptions;
    private readonly IModelBinderFactory _modelBinderFactory;
    private readonly IModelMetadataProvider _modelMetadataProvider;

    public DefaultModelBinder(
        IOptionsSnapshot<JsonOptions> jsonOptions,
        IModelBinderFactory modelBinderFactory,
        IModelMetadataProvider modelMetadataProvider)
    {
        _jsonOptions = jsonOptions;
        _jsonOptions.Value.JsonSerializerOptions.MaxDepth = 0;
        _modelBinderFactory = modelBinderFactory;
        _modelMetadataProvider = modelMetadataProvider;
    }

    public async Task<TRequest> BindAsync<TRequest>(HttpContext context)
    {
        return (TRequest)await BindInternal(context, typeof(TRequest));
    }

    private async Task<object> BindInternal(HttpContext context, Type modelType)
    {
        var routeProvider = new RouteValueProvider(BindingSource.Path, context.Request.RouteValues);
        var queryProvider = new QueryStringValueProvider(BindingSource.Query, context.Request.Query, CultureInfo.InvariantCulture);
        var compositeValueProvider = new CompositeValueProvider
        {
            routeProvider,
            queryProvider
        };
        IValueProvider formProvider = null;
        var bodyProvider = new JsonBodyValueProvider(context, _jsonOptions);
        if (context.Request.HasFormContentType)
        {
            formProvider = new FormValueProvider(BindingSource.Form, context.Request.Form, CultureInfo.CurrentCulture); ;
            compositeValueProvider.Add(formProvider);
        }
        else
        {
            compositeValueProvider.Add(bodyProvider);
        }

        var modelMetadata = _modelMetadataProvider.GetMetadataForType(modelType);

        if (modelMetadata.BoundConstructor != null)
        {
            throw new NotSupportedException("Record type not supported");
        }

        var modelState = new ModelStateDictionary();

        var modelBindingContext = DefaultModelBindingContext.CreateBindingContext(
            new ActionContext(context, context.GetRouteData(), new ActionDescriptor(), modelState),
            compositeValueProvider,
            modelMetadata,
            bindingInfo: null,
            modelName: "");

        modelBindingContext.Model = Activator.CreateInstance(modelType);
        modelBindingContext.PropertyFilter = _ => true; // All props

        var factoryContext = new ModelBinderFactoryContext()
        {
            Metadata = modelMetadata,
            BindingInfo = new BindingInfo()
            {
                BinderModelName = modelMetadata.BinderModelName,
                BinderType = modelMetadata.BinderType,
                BindingSource = modelMetadata.BindingSource,
                PropertyFilterProvider = modelMetadata.PropertyFilterProvider,
            },

            // We're using the model metadata as the cache token here so that TryUpdateModelAsync calls
            // for the same model type can share a binder. This won't overlap with normal model binding
            // operations because they use the ParameterDescriptor for the token.
            CacheToken = modelMetadata,
        };
        var binder = _modelBinderFactory.CreateBinder(factoryContext);

        await binder.BindModelAsync(modelBindingContext);

        return modelBindingContext.Result.Model;
    }
}

```
As you can see it is dependent on some `Microsoft.AspNetCore.Mvc.ModelBinding` namespace types to do its work.  This will use the default set of MVC binders and their respective binding providers (the things that determine which binder to use).  If a dev requires custom binding then they write their own provider and binder and register the provider with MVC options at startup, just as they would for controllers.

This is dependent on MVC for model binding however so I guess that comes down to whether the package continues to support netstandard or just moves onward with net5.0, 6.0, etc.  Tradeoff between reach and functionality I guess.  There is talk on .net 6.0 roadmap that may suggest model binding may become less coupled but nothing is concrete.

As for how to obtain the bound model the extension would suffice I imagine.  Just to clarify though that the TModel here is specific to the particular request handler or subscriber, i.e. the TModel each subscriber binds would be different to the request handler's TModel.   They all can use different TModel types basically even though they are coupled by their Route attribute.  Thoughts?

As for typed handlers, yes I knew that would complicate things with the Handle method.  Nothing like a challenge :-)

The convention approach is also very interesting too.  Like you said, one step at a time.

**Comment by mauroservienti** [comment]
Wow, once again thanks for the code @markphillips100.

> This is dependent on MVC for model binding however so I guess that comes down to whether the package continues to support netstandard or just moves onward with net5.0, 6.0, etc. Tradeoff between reach and functionality I guess. There is talk on .net 6.0 roadmap that may suggest model binding may become less coupled but nothing is concrete.

.NET Standard  is already an option anymore. To use endpoints and endpoint builders the code must use at least .NET Core 3.x. In 1.8.0 I'm deprecating the legacy stuff and the plan is that 2.0 will be .NET Core 3.x (or 5.x) at the very minimum.

That means that the dependency on MVC stuff is less of a problem.

Thanks again, hopefully I'll be able to spike it soon.

**Comment by mauroservienti** [comment]
@markphillips100 I'm spiking options, looking at your sample code it's not clear to me what `JsonBodyValueProvider` is. I implemented a trivial `IValueProvider` that works for the spike, but it's hardcoded for the spike. Can you help me?

**Comment by markphillips100** [comment]
In short, we can do away with all that value provider 'setup' code, including the custom Json body provider. :-)

I was never really happy with the usage of the `CompositeValueProvider` in the code I posted - it was code from another source.  Delving a little deeper into AspNetCore and it's apparent this type has a factory method for obtaining a 'relevant' composition of IValueProviders based on the ActionContext and the default MvcOptions' ValueProviderFactories property.

The code below supports the notion that the MVC model binding is controlled completely by MvcOptions for which the defaults are usually sufficient but also support the inherit extensibility, i.e. you get support for FromBody, FromForm, FromRoute, FromQuery, and others out-of-the-box.

```
public class DefaultModelBinder : IModelBinder
{
    private readonly IModelBinderFactory _modelBinderFactory;
    private readonly IModelMetadataProvider _modelMetadataProvider;
    private readonly IOptions<MvcOptions> _mvcOptions;

    public DefaultModelBinder(
        IModelBinderFactory modelBinderFactory,
        IModelMetadataProvider modelMetadataProvider,
        IOptions<MvcOptions> mvcOptions)
    {
        _modelBinderFactory = modelBinderFactory;
        _modelMetadataProvider = modelMetadataProvider;
        _mvcOptions = mvcOptions;
    }

    public async Task<TRequest> BindAsync<TRequest>(HttpContext context)
    {
        return (TRequest)await BindInternal(context, typeof(TRequest));
    }

    private async Task<object> BindInternal(HttpContext context, Type modelType)
    {
        var modelState = new ModelStateDictionary();
        var actionContext = new ActionContext(context, context.GetRouteData(), new ActionDescriptor(), modelState);
        var valueProvider = await CompositeValueProvider.CreateAsync(actionContext, _mvcOptions.Value.ValueProviderFactories);
        var modelMetadata = _modelMetadataProvider.GetMetadataForType(modelType);

        if (modelMetadata.BoundConstructor != null)
        {
            throw new NotSupportedException("Record type not supported");
        }

        var modelBindingContext = DefaultModelBindingContext.CreateBindingContext(
            actionContext,
            valueProvider,
            modelMetadata,
            bindingInfo: null,
            modelName: "");

        modelBindingContext.Model = Activator.CreateInstance(modelType);
        modelBindingContext.PropertyFilter = _ => true; // All props

        var factoryContext = new ModelBinderFactoryContext()
        {
            Metadata = modelMetadata,
            BindingInfo = new BindingInfo()
            {
                BinderModelName = modelMetadata.BinderModelName,
                BinderType = modelMetadata.BinderType,
                BindingSource = modelMetadata.BindingSource,
                PropertyFilterProvider = modelMetadata.PropertyFilterProvider,
            },
            CacheToken = modelMetadata,
        };

        await _modelBinderFactory
            .CreateBinder(factoryContext)
            .BindModelAsync(modelBindingContext);

        return modelBindingContext.Result.Model;
    }
}
```

In a normal controller action binding would occur with the action's parameters, for example:

```... MyAction([FromRoute] Guid id, [FromBody] Command command);```

This package doesn't use parameters so instead we can encapsulate the equivalent of an action's parameters inside a 'request' class.  Using our example:

```
public class MyRequest
{
    [FromRoute]
    public Guid Id { get; set; }
    [FromBody]
    public Command Command { get; set; }
}
```

This type is then bound using:

```
var requestModel = await _modelBinder.BindAsync<MyRequest>(request.HttpContext);
```

**Comment by mauroservienti** [comment]
Thanks! It's more or less what I understood yesterday while spelunking into ASP.Net source code. Which is interesting because if I understood correctly it uses the defined input formatters, that is another thing I was looking to support.

**Comment by markphillips100** [comment]
That's correct.  The body binder for example would use the configured mvc input formatter.

**Comment by mauroservienti** [comment]
I got a basic implementation working in a test in #258, thanks for your support @markphillips100

**Comment by mauroservienti** [comment]
@markphillips100 other than offering a `Bind<>` extension method for HttpRequest that does what you proposed and requires the user to define the wrapper class, what do you think about allowing something like:

```
var body = request.BindFromBody<MyBodyModel>()
```

where `MyBodyModel` is just a POCO. And the `BindFromBody` does something like:

```
class InternalBodyWrapper<TBody>
{
   [FromBody]
   public TBody Body{ get; set; }
}

static TBody BindFromBody<TBody>(this HttpRequest request)
{
    var binder = ...
    var wrapper = binder.Bind<InternalBodyWrapper<TBody>>(request);
    return wrapper.Body;
}
```

Using the same approach there could be a `BindFromForm`, `BindFromRoute`, etc.

In designing unit tests I perceive as extremely annoying the need of designing the wrapper class.

**Comment by markphillips100** [comment]
Is it annoying because the binder currently creates the instance or because you have to define the binding using attributes?  If the former, I'm happy to surface an additional/alternate method that accepts an instance of the model as a parameter.  For example, I just added a 2nd bind overload (in my version) to do just that:
```
public interface IModelBinder
{
    Task<TRequest> BindAsync<TRequest>(HttpContext context);
    Task<TRequest> BindAsync<TRequest>(HttpContext context, TRequest request);
}
```
If it's a case of a desire to hide the need for attributes for those that want a different way of binding I don't have a problem.  Surfacing both just broadens the reach in my opinion.  However, I see some problems.

This might seem to work for the Body but I'm not sure it works for Route, Query and Form attributes.  These attributes require either a constant string for a name value or will imply one from the property's name.  This would seem to prevent a wrapper that hides the attribute from the consumer would it not?

I feel the binding (in my opinion) should be governed by the model class and property attributes in a similar way that a controller action method's property attributes govern its binding.  So for me I see no problem with writing a model with attributes as it is a similar usage pattern to MVC.  Whilst it does intrinsically couple the model to the surface HTTP API (good or bad?), it does mean I don't need to provide a mapping implementation of sorts that encapsulates several binding calls to build a DTO (that doesn't have attributes).

My typical use case for the model is a command payload that I pass to [Mediatr](https://www.nuget.org/packages/MediatR/).  The example below is using the method (mentioned above) that accepts an instance of the model to bind to.  In this case the model is an instance of Mediator's `IQueryRequest` so it can be passed direct to Mediator.

```
public class Query : IQueryRequest<Result<CartViewModel>>
{
    [FromRoute]
    public Guid OrderId { get; set; }
}

public async Task Handle(HttpRequest request)
{
    var requestModel = new Cart.Query();
    await _modelBinder.BindAsync(request.HttpContext, requestModel);

    var result = await _mediator.Send(requestModel);
    ...
}
```
What I hope to do (for myself) is wrap the Bind and Send into a single interface (of my own) to avoid a dev having to remember to call Bind, just to further encapsulate the binding step.  This brings the usage pattern for binding very close to MVC's controller object binding. For example you can do the following with a controller and have the model's properties bind (using attributes).
```
public Task<ActionResult<CartViewModel>> Get(Cart.Query requestModel, CancellationToken cancellationToken = default)
```

Now, my model example is very simple but I do have some models that bind to several route constraints, and several query values (with name aliases) and also the body or form values, all in one class using attributes.  To discard the attributes from the DTO and instead introduce a mapping class with bind calls would seem to complicate this use case.  What do you think?

**Comment by markphillips100** [comment]
I should have also said that my Bind and Send aggregate at the end of my last post isn't necessary if we had a generic ICompositionRequestsHandler as one would assume the model passed to the Handle<TRequest> would already be bound....just as in MVC.  Way down the road of course. :-)

I may have missed the point entirely re your proposal though.  Have I interpreted the use case correctly or did you mean for the extensions to only be used to help with testing?

**Comment by mauroservienti** [comment]
Thanks, @markphillips100. I'll comment later today. Meanwhile, I think the feature is ready. Would you have time for a review https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/262?

**Comment by mauroservienti** [comment]
> I should have also said that my Bind and Send aggregate at the end of my last post isn't necessary if we had a generic ICompositionRequestsHandler as one would assume the model passed to the Handle<TRequest> would already be bound....just as in MVC.  Way down the road of course. :-)

With what we have now that doesn't seem too far away anymore 😉 and that's mostly due to your help.

> I may have missed the point entirely re your proposal though.  Have I interpreted the use case correctly or did you mean for the extensions to only be used to help with testing?

While writing tests I had a feeling that the task of creating a wrapper class was too repetitive. But in the end I think I'm wrong, it's just in the tests scenario that it's boring simply because the test model is more it less always the same. In a real project that problem disappears. So, disregard my idea, it doesn't make much sense and as you pointed out works only for bodies and forms.

**Comment by mauroservienti** [comment]
PR merged.

> My typical use case for the model is a command payload that I pass to [Mediatr](https://www.nuget.org/packages/MediatR/).  The example below is using the method (mentioned above) that accepts an instance of the model to bind to.  In this case the model is an instance of Mediator's `IQueryRequest` so it can be passed direct to Mediator.


Raised https://github.com/ServiceComposer/ServiceComposer.AspNetCore/issues/274 to keep track of that.
