### ISSUE TITLE
Does it make sense to swap the assembly scanning custom implementation with Scrutor?

### ISSUE THREAD

**Issue by mauroservienti** [ServiceComposer/ServiceComposer.AspNetCore#305]

**Comment by markphillips100** [comment]
I think Scrutor is only for DI service registration isn't it?  This would make it insufficient wouldn't it considering the needs of the CompositionMetadataRegistry?

**Comment by mauroservienti** [comment]
Scrutor is primarily for assembly scanning and retrieving types at runtime, registration would then be performed the usual way. But I'm not sure what the problem I was trying to solve was when I raised this 😄 

Closing. It can always be resurrected.
