### ISSUE TITLE
DotNet 6 minimal API question

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#310]
Have you heard of the pending .net 6 minimal APIs?  Just wondering if they add value to your work in regards to model binding and more specifically versioning perhaps, or I guess whether their inclusion in .net have an impact on any future direction servicecomposer takes.

**Comment by mauroservienti** [comment]
Thanks for your patience @markphillips100.

> Have you heard of the pending .net 6 minimal APIs?

I did, yes.

> Just wondering if they add value to your work in regards to model binding and more specifically versioning perhaps, or I guess whether their inclusion in .net have an impact on any future direction servicecomposer takes.

I'm not sure what type of usage we could do of the minimal API in ServiceComposer. Do you have any idea in mind?

**Comment by markphillips100** [comment]
Not really. I'm not even sure if there's value in them at this point. Will close issue and wait for 6 to be released. See what the community makes of them 😁
