### ISSUE TITLE
Client model question

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#311]
Let me know if this is the wrong place for this question @mauroservienti .  It touches on viewmodel composition which is really the reason for me putting it here.

I'd appreciate some guidance, insight or just some thoughts on something I've been contemplating in regards what to do about model code (DTO stuff) that resides in client apps that consume viewmodel composition APIs.  Specifically, should the code exist in the same repo as a client (say mobile app, blazor, angular or other native/browser client), or should each client be provided a package built from code owned by the relevant business service.

I'll try to setup a scenario to explain further.

In a "UI" composition scenario it is fairly obvious that each business service supplies all its UI components and any client model code to interact with the service's APIs.  The UI widgets/components and their model are encapsulated within the business service basically.  And importantly, the client model aligns with the server model on a versioned deployment level.

In a ViewModel composition scenario the above situation is possible but only where another service has no viewmodel composition subscriber to the same url, i.e. the client model is no longer fully encapsulated by the one business service.  Sort of the point of the whole composition thing really.

The fact the client model (for a given URL) is no longer owned in full by any particular service makes me ponder 4 possible strategies; 

1. Keep all hand-written client model code and data access code within each client app and live with some possible duplication across apps that happen to use the same URLs.
2. Use dictionary service-specific keyed view models and split the responsibility/ownership of the code along service boundary lines in terms of which service owns their part of the viewmodel dictionary and reduce the client model code that resides in client apps to only the composed model.
3. Use merged view models (or dictionaries) instead of service-specific dictionary and codify the resulting composed model in the server app hosts repository, i.e. packaged and deployed when host apps are deployed.  This effectively creates a client sdk versioned along with the composed server API version.  Also then different packages can be created to support different clients, say .net for blazor, or dart for Flutter mobile, etc.
4. Write an OpenApi (Swagger) spec by hand (no auto generation at a composition level) that matches the composition model that would be surfaced by inclusion in a server api.  Client apps then generate their client models from the spec.

3 or 4 are more preferable in my opinion although both require manually detecting changes to a service's viewmodel component in order to keep a client model in sync.

I was worried about coupling but as this is the host apps repository then it's okay to do it here, i.e. it's here that the decision is made about which apps reference which viewmodel composition components so makes sense to also compose the required client sdk here too.

Do you have any thoughts on this stuff?

**Comment by mauroservienti** [comment]
For some reasons, this issue disappeared from my GitHub notifications. Sorry about that.

> I'd appreciate some guidance, insight or just some thoughts on something I've been contemplating in regards what to do about model code (DTO stuff) that resides in client apps that consume viewmodel composition APIs. Specifically, should the code exist in the same repo as a client (say mobile app, blazor, angular or other native/browser client), or should each client be provided a package built from code owned by the relevant business service.

I guess that at this point the main differentiator is: are you using a branding approach (e.i. the UI is monolithic) and thus it makes sense that ViewModels DTOs are defined in the client application. Otherwise it makes more sense that they are defined and shipped by services, with the downside that you'll start dealing with complex stuff. Due to the ViewModel being the result of a composition, if it is strongly typed it should be split across multiple services, but that's hard to achieve with C#. The only thing that comes to my mind is source generators in combination with partial classes.

> In a "UI" composition scenario it is fairly obvious that each business service supplies all its UI components and any client model code to interact with the service's APIs. The UI widgets/components and their model are encapsulated within the business service basically. And importantly, the client model aligns with the server model on a versioned deployment level.
> 
> In a ViewModel composition scenario the above situation is possible but only where another service has no viewmodel composition subscriber to the same url, i.e. the client model is no longer fully encapsulated by the one business service. Sort of the point of the whole composition thing really.
> 
> The fact the client model (for a given URL) is no longer owned in full by any particular service makes me ponder 4 possible strategies;
> 
> 1. Keep all hand-written client model code and data access code within each client app and live with some possible duplication across apps that happen to use the same URLs.

💯, this comes with some coupling for sure. I'm wondering if it's a problem or not in your scenario. The coupling I mean.

> 2. Use dictionary service-specific keyed view models and split the responsibility/ownership of the code along service boundary lines in terms of which service owns their part of the viewmodel dictionary and reduce the client model code that resides in client apps to only the composed model.

Which would be like using `dynamic`, wouldn't it?

> 3. Use merged view models (or dictionaries) instead of service-specific dictionary and codify the resulting composed model in the server app hosts repository, i.e. packaged and deployed when host apps are deployed.  This effectively creates a client sdk versioned along with the composed server API version.  Also then different packages can be created to support different clients, say .net for blazor, or dart for Flutter mobile, etc.

This is interesting and aligns well with my idea about partial classes and source generators, for .NET/C#.

> 4. Write an OpenApi (Swagger) spec by hand (no auto generation at a composition level) that matches the composition model that would be surfaced by inclusion in a server api.  Client apps then generate their client models from the spec.

This would the best approach, IMO. I'm still thinking about why there is no way to automate it. There is a bug in the back of my mind that tortures me about this 😄 

> 3 or 4 are more preferable in my opinion although both require manually detecting changes to a service's viewmodel component in order to keep a client model in sync.

They could be tested using some approval testing techniques, though.

**Comment by markphillips100** [comment]
Thanks for the response @mauroservienti .  Really appreciate it.

I do use the branding approach, i.e. a monolithic UI, from both a Blazor wasm app and 3 Flutter mobile apps.  These consume a bunch of different APIs, some composition, some controllers, some provided by business services, some by ITOps too. For now, those APIs are all in the "mobile api" host but nothing prevents hosting some controller-based APIs elsewhere if needs be.

The latter 3 mobile apps cross very similar concerns to each other but play different roles, this does mean they share a lot of the surfaced APIs, so I've tried to encapsulate access to the APIs using a library of code that layers the concerns of a client SDK.  So taking a "clean architecture" approach, it only surfaces abstractions and models. DTOs, mappers, and API access code is hidden away basically.

I hoped one day to auto-generate the DTO and API access code in that lib, and then only be concerned with mapping logic.  This is possible if swagger is available, and still leaves responsibility for those DTOs with the client app - it being monolithic so justly should be responsible.  It's only possible though for the controller-based APIs.

As for structure of the lib, I try as much as possible to align a folder structure to where the API originates. An attempt at being modular.  For example, if ITOps surfaces a set of APIs from a specific component then I'd have an equivalent named folder to keep the relevant DTO types together, and then of course have a single file to encapsulate the API access methods for calling the relevant URLs specific to that backend component.

This is all fine until say a Sales service is surfacing a composition API with many subscribers.  The composed client model doesn't fit in any aligned folder structure.  It sort of sits at the top, or a separate "composition" folder entirely.  This being due to it needing to include types from other business and/or itops representative client folders.

In regards to the approaches, the dictionary, or dynamic, approach means the lib surfaces an equivalent dictionary or dynamic (assuming the client code supports it, which it does here) for a given composition request.  The downside here is that now the client consuming code now needs to have knowledge of the type a key should be.  I mean, it does need to know a type's properties anyway if it were strongly typed, but now the issue is a change to a given key's type isn't captured at compile time.  You could argue that a breaking change at the API would cause an equally bad runtime issue in the client's deserialization perhaps but then that comes down to whether the deserialization in the client is actually deserializing to concrete types or leaving as dynamic.  It all sounds a bit messy.

> This is interesting and aligns well with my idea about partial classes and source generators, for .NET/C#.

I'm curious, intrigued and excited about the possibility of a merged viewmodel at the server.  Just no idea how.

> This would the best approach, IMO. I'm still thinking about why there is no way to automate it. There is a bug in the back of my mind that tortures me about this

I feel the same.  It just feels like the host should be surfacing documentation about the APIs it generates.  And I also keep thinking there should be a way to just annotate handlers and subscribers in a way that a (custom) swagger API explorer can use to generate swagger.json.

I'm hoping to get a look at the dotnet 6 minimal API swagger support in time as that deviates from the controller approach and has a separate swagger "EndpointsAPIExplorer" so was hoping it could trigger some lightbulb.

Anyway, thanks again Mauro.

**Comment by markphillips100** [comment]
I'll close this @mauroservienti as hoping the source generator approach leads somewhere fruitful....when I get more spare time that is. :-(
