### ISSUE TITLE
ITOps services and query result composition

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#339]
This is not an issue with service composer @mauroservienti , more me trying to understand its relevance or applicability when it comes to ITOps services.  FYI, I've been following your notification related posts at [milestone.topics.it](https://milestone.topics.it/) and I've applied similar concepts to my ecommerce project  - I wonder if  I'll ever get to prod :-( - but I've come across an area of concern I'm not sure of and would appreciate your insights in the context of SOA and this lib.

Like your notification service, my discounts and fees service is an ITOps service.  I made this decision due to the fact discounts and fees are concerns that more than one business area might want to have a play with, e.g. delivery/shipping service might want to describe a delivery fee and a discount fee, sales may want a small order fee, etc.  So business services describe their discount and fee types much like your business services tell notification service about events that can be subscribed.

The actual instances of discounts and fees are created directly with the itops discount and fees service, based on the type of those available.  In the same way, your notification service allows users to subscribe by directly interacting with the ITOps service.  Point being that the business service only describe what should be creatable/subscribed, and they do not get involved in the persistence of the instances.  In some way, the business services do not own the instance data, only the types. The ITOps service owns the instances.

So, the conundrum. If the ITOps service owns the data, can it (or should it) be allowed to surface a component that subscribes to a business service's service composition route?  Let's say /cart/{id} for example?  Or, should the composition only ever occur from business services?

**Comment by markphillips100** [comment]
The more I think about this the more I think it just doesn't make sense for an ITOps component to be even aware of the URLs surfaced by business services.  It should only ever surface its own URLs, and can't think of any reason why these wouldn't always be controller actions too.  Composition should be something only done across business services.

**Comment by mauroservienti** [comment]
If I understand the use case correctly, aren't there two different operations at play here?

1. The need to define rules around discounts and fees, the authoring tool
2. The need to apply discount and fees rules, the rules engine

For the first one, users (back-office users, I guess) interact with an interface that manipulates the ITOps thing. As you said, ITOps owns the data. So it seems to me (thinking out loud here) that ITOps could deploy a "discounts and fees" component. The component will be loaded into a sort of rule engine/pipeline that, for example, allows sales and shipping to input base prices. Prices go through the pipeline, and one of the behaviors in the pipeline is the one provided by ITOps that can load defined rules and apply them.

**Comment by markphillips100** [comment]
That's how I see it too.

I guess I was more thinking about the output of the charging engine, i.e. surfacing it as a model of data in the context of a cart request.

I'm not sure if it's correct or not but my thinking is that the result of the pipeline belongs with the business service that triggered it, meaning they get to decide what to do with that output data. For example, perhaps the Finance service triggered the pipeline in order to obtain a summary and total - it would need a total to charge the customer at checkout time.

So, Finance owns the summary and total values, it can then present those when handling its subscription to /cart/{id}, rather than ITOps persisting engine outcomes and surfacing those for cart urls.  Does that statement seem okay to you?

**Comment by mauroservienti** [comment]
> So, Finance owns the summary and total values, it can then present those when handling its subscription to /cart/{id}, rather than ITOps persisting engine outcomes and surfacing those for cart urls. Does that statement seem okay to you?

Yes, I think it makes a lot of sense. I go on thinking that IT/Ops is a logical concept that has no place in the physical world. By that I mean that logically there is someone that owns that process (the pipeline we're talking about here), and thus that owner can do whatever it needs to do with the result of the execution.

**Comment by markphillips100** [comment]
Thanks @mauroservienti .  Appreciate the feedback.
