### ISSUE TITLE
Issue casued by Task.WhenAll when underlying tasks use types that are not threadsafe

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#360]
I'm not sure if this is something that should be changed but at least to be aware of.

The use of `await Task.WhenAll(pending)` [here](https://github.com/ServiceComposer/ServiceComposer.AspNetCore/blob/474664fb899fdb3edd8d87b7802b8f5ed8ca7a9c/src/ServiceComposer.AspNetCore/CompositionHandler.cs#L62) will allow multiple threads to be used for each Task, so if any shared scoped instance of something is used across task handlers it's vital that it is thread safe.

If we use direct database access from composition handlers using an EFCore DBContext we should be aware that it is not thread safe. This is a pattern I use a fair bit now, rather than an intermediary web API, and I've just come across a thread safe problem.

Normally we wouldn't come across a situation where usage of DBContext would be a problem as it would be expected that the composition handler provided by each service only makes use of its own service's DbContext.  As it should be.

However, say we have a handler in one service  that makes use of an ITOps abstraction, say some calculation engine of sorts. Any of the services could supply their own implementation of the calculation abstraction which can also inject their own service's DbContext.

This brings the possibility of a single service's scoped DbContext instance being used in two threads at once, one from a composition handler supplied by the service, and another used by the calculation implementation that is indirectly plugged into the call stack of another service's composition handler.  It's a non-deterministic problem so it's alluded me for a long time but I've encountered it a few times in recent days, mostly I think because I'm testing out release builds locally.

There are only two solutions as I see it:
1. Swap `Task.WhenAll(pending)` for a regular `forloop` and `await` each handler call individually.  This has the downside of increasing the total composition time as there's no longer any parallelism.
2. Inject an IServiceProvider into the "engine" and use it to create a new DI scope so any downstream DBContext used by it is a new instance.  I don't think there's necessarily a downside in doing this, just effort.

I'm going to go with no. 2 as I don't think we should give up the composition handler parallelism so easily.  I wondered if you've come across this issue yourself, and even maybe found alternative ways to resolve it?

**Comment by mauroservienti** [comment]
Thanks for looking into this @markphillips100. I never faced the issue myself but always suspected it was there.

Would it be interesting to have an extension point before each handler invocation? The extension point could expose the service provider and allow the creation of a child scope for each handler if needed?

**Comment by markphillips100** [comment]
Not sure that it's needed, or more specifically, something that this lib should provide and best left for developers to supply it themselves as required.

For example, I tend to have small handlers which pass a request type to a mediator.  The implementation of those mediator commands can inject IServiceProvider if they require it.  So in my case having the handler be supplied IServiceProvider would end up not being used as mediator wouldn't (cannot) use it directly.  

I guess I just wanted to maybe surface it in documentation perhaps that developers should be aware of the thread safety being imposed is all.  Just a note perhaps, what do you think?

**Comment by mauroservienti** [comment]
Makes sense to at least provide some documentation. I'll craft it. Thanks.

**Comment by mauroservienti** [comment]
Raised https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/371. @markphillips100 can you have a look?

**Comment by markphillips100** [comment]
Looks good @mauroservienti
