### ISSUE TITLE
AssemblyScanning not finding types when using a self-contained exe on linux

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#361]
I'm experimenting with publish of projects to self-contained exe so that trimming can be applied.  The publish output targets linux so the self contained output is not appended with ".exe", as it would be on a windows publish. As a result the scanner won't find the file containing handlers due to the restriction on file extension [here](https://github.com/ServiceComposer/ServiceComposer.AspNetCore/blob/474664fb899fdb3edd8d87b7802b8f5ed8ca7a9c/src/ServiceComposer.AspNetCore/AssemblyScanner.cs#L17).

Is it possible to make this search pattern configurable so I could maybe do the following?

```
options.AssemblyScanner.AssemblySearchPatternsToUse = { "*.dll", "MyApp" }
```

**Comment by markphillips100** [comment]
Hmm, it's also possible the AssemblyValidator would need to bypass the assembly validation step for selfcontained exe - I don't think it has metadata anymore as it's no longer a PE.

**Comment by mauroservienti** [comment]
@markphillips100 I see no issues in exposing more scanner options. It's easy to explore scanning patterns and the scanner could also allow to inject a predicate to customize validation for each assembly.

**Comment by markphillips100** [comment]
I'm going to leave the self-contained approach for a bit.  Too many issues trying to prevent components from being trimmed just because they are dynamically registered at runtime.  This "plugin" type strategy generally doesn't work well with trimming but was hoping I could just inform the build/publish to always keep my libs and just trim dotnet stuff.  No joy though.

Oh well, will just have to make do with the 80Mb of dotnet bloat in my docker containers.

I'll close the issue and can reopen in the future if necessary, but for now the current capability for scanning is fine for non-trimming use cases.  Sorry to bother you @mauroservienti .

**Comment by mauroservienti** [comment]
No worries @markphillips100. If you're building Docker containers why not use the explicit API to register handlers (the same used by tests)? Containers are immutable and assembly scanning and types discovery don't make much sense.

**Comment by markphillips100** [comment]
My host project merely adds references to many service component NuGet packages. It's responsible for setting up scanning and discovering all components for various functions (composition, mediatr commands, validators, MVC application parts, etc) and registering as appropriate by mere implementation of an interface. So there are multiple scans depending on what function is initialised. Whether the output is immutable or not there's value in not having the host care about explicit setup, beyond the generalised scan setup I mean.

Libraries like mediatr as an example provide their own discovery mechanism precisely to avoid explicit registration of request handlers.

On balance, I think there's just more value with a scan approach rather than attempting to shrink the container image by 80Mb (maybe less). Would you agree?

**Comment by markphillips100** [comment]
Just a bit of info @mauroservienti in case you were interested. I've been confusing "self contained" with "single file".  The two are very different concerns when it comes to publishing dotnet.  Seems trimming is still possible when you target a specific runtime with self-contained enabled (default when runtime specified).

So long as I **don't** use PublishSingleFile also when it comes to the dotnet publish everything still works in terms of scanning with the added benefit of reduced image size.
