### ISSUE TITLE
Can MapCompositionHandlers return IEndpointConventionBuilder?

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#369]
I'm attempting to refactor a Blazor host's security to use DuendeSoftware's "BFF" approach.  In part this entails adding an attribute or metadata to endpoints that should have some "extra security" checks done.

The main way they apply this metadata is by use of an extension applied to the result of `MapControllers()`.  I've never noticed before but this extension (and other MVC extensions) returns an `IEndpointConventionBuilder`.  So it would seem this allows customization of endpoints beyond what the original "map..." extension does.

Unfortunately, the `MapCompositionHandlers` does not return such an interface so doesn't support this level of customization once endpoints are mapped.  There is an alternative and that's to apply the attribute I need explicitly to each and every composition handler, however this is not something I'd prefer to do as it directly couples those service component libraries to the custom authentication used.

Do you think it might be possible to take a look and see if the endpoint registration can support this interface?

**Comment by mauroservienti** [comment]
hey @markphillips100,

I just had a look at it, and I'm not sure I understand how it works. `IEndpointConventionBuilder` looks like the following:

```
public interface IEndpointConventionBuilder
{
   void Add(Action<EndpointBuilder> convention);
}
```

We could easily create a class that implements the interface, however, it's not clear to me how it should behave. Let me dump my train of thoughts here. The result you want to achieve is something like the following:

```
IEndpointConventionBuilder conventions = endpoints.MapCompositionHandlers()
conventions.DoSomethingElse();
```

As of now, `MapCompositionHandlers` creates all the required `EndpointBuilder` instances later used by ASP.Net to create endpoints and operate. We could create an implementation of `IEndpointConventionBuilder` (it's trivial) that keeps track of all the created `EndpointBuilder` instances and collects conventions.

What's not clear to me is who is responsible to apply those conventions. I tried to dive into the ASP.Net source code and it's a mess 😄 (I wasn't expecting anything less). What I noticed is that they seem to delay the endpoints creation at a later stage where conventions are already created and can be applied to the `EndpointBuilder`. What I'm missing is how that later stage is triggered.

**Comment by mauroservienti** [comment]
Scratch that, I think it's easier than I thought. I'll raise a PR.

**Comment by mauroservienti** [comment]
Here is a possible implementation https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/370
It's on `master` so it'll target 2.0.0, but if that's what you expect it can be backported to 1.13.

**Comment by markphillips100** [comment]
That's awesome @mauroservienti .  I'll take a detailed look over the weekend for certain.

**Comment by markphillips100** [comment]
I've confirmed this approach satisfies my needs @mauroservienti .

Is a 1.13 possible?  I think I'd also need #373 update too though.  If you think it's best to put them in a v2 though I understand.

**Comment by mauroservienti** [comment]
I think back-porting both to 1.13 is possible. I'm a bit overwhelmed and overcommitted this week. Hopefully, I should have some time towards the end of the week (if the little 4yo Dracula 🧛‍♂️ goes back to school and stops spreading killer viruses 🦠 at home... 😬). Otherwise, beginning of next week.

**Comment by markphillips100** [comment]
Your health is more important @mauroservienti .  It'll get done in due course I'm sure so take care of yourself (and Dracula) first.

**Comment by mauroservienti** [comment]
#370 is merged to `master`, raised https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/377 to back-port to `release-1.13`

**Comment by mauroservienti** [comment]
`1.13.0` is on [NuGet](https://www.nuget.org/packages/ServiceComposer.AspNetCore/1.13.0)
