### ISSUE TITLE
Add IConfiguration to ViewModelCompositionOptions

### ISSUE THREAD

**Issue by markphillips100** [ServiceComposer/ServiceComposer.AspNetCore#373]
I've been bad and used `services.BuildServiceProvider().GetService<IConfiguration>()` in many of my component's service collection extensions where I might need access to some config to help configure the DI setup.  Using `BuildServiceProvider()` is a bit frowned on, due to singleton lifecycles (apparently).

I've refactored many of my configuration extensions to surface the `IConfiguration` abstraction as a parameter and pass the instance available during startup's `ConfgureServices`.  This is all fine except for cases where I make use of `IViewModelCompositionOptionsCustomization` to register a component's deps.  At the moment I have no choice but to use the aforementioned badness.

Is it possible, or is it a smell, to add the abstraction to `ViewModelCompositionOptions` so that it can be available during the `Customize` calls?

**Comment by mauroservienti** [comment]
That makes a lot of sense. I'll take a look at what's the easiest way to expose it.

**Comment by mauroservienti** [comment]
The easiest thing that comes to my mind is in https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/374. It's ugly 😢 

Any suggestion is appreciated.

**Comment by markphillips100** [comment]
That approach was all I could think of too. It doesn't effect the customization abstraction and allows for optionally supporting IConfiguration, so minimal impact on existing usage.

**Comment by mauroservienti** [comment]
Thanks. Agreed. I'm thinking about throwing an exception with an explanation message in the `Configuration` property getter if it's null. It's better than a NRE and the message could guide to using the correct `AddViewModelComposition` overload.

**Comment by markphillips100** [comment]
That's a good idea

**Comment by mauroservienti** [comment]
Another option, for 2.0.0, but not for 1.13 because I think it's a breaking change, would be to enable nullable reference types and make the `IConfiguration? Configuration` nullable.

Do you have any preference? I'm leaning towards the exception because it allows for a meaningful message explaining how to fix the issue.

**Comment by markphillips100** [comment]
A nullable reference library would be a good move I think but I agree it should be saved for a major bump.  As for the message in the nullable ref use case, probably sufficient to just have a doc comment on the property for intellisense.

**Comment by mauroservienti** [comment]
`1.13.0` is on [NuGet](https://www.nuget.org/packages/ServiceComposer.AspNetCore/1.13.0)
