### ISSUE TITLE
Investigate how to get rid of Json.Net and use System.Text.Json

### ISSUE THREAD

**Issue by mauroservienti** [ServiceComposer/ServiceComposer.AspNetCore#589]

**Comment by andreasohlund** [comment]
This is done right?

**Comment by mauroservienti** [comment]
Correct. Done in https://github.com/ServiceComposer/ServiceComposer.AspNetCore/pull/765

**Comment by mauroservienti** [comment]
And released in https://github.com/ServiceComposer/ServiceComposer.AspNetCore/releases/tag/4.0.0
